package persistence;

import domain.User;
import org.mindrot.jbcrypt.BCrypt;

import java.sql.*;
import java.util.ArrayList;
import java.util.List;
import java.util.Optional;

public class UserDAO {

    private final Connection connection;

    public UserDAO(Connection connection) { this.connection = connection; }

    // ID is auto-generated by DB (SERIAL) — user object's id field is ignored on insert
    public void addUser(User user, String rawPassword) throws SQLException {
        String sql = "INSERT INTO users(name,email,phone_number,username,password_hash,role) " +
                     "VALUES(?,?,?,?,?,?)";
        try (PreparedStatement s = connection.prepareStatement(sql)) {
            s.setString(1, user.getName());
            s.setString(2, user.getEmail());
            s.setString(3, user.getPhoneNumber());
            s.setString(4, user.getUsername());
            s.setString(5, BCrypt.hashpw(rawPassword, BCrypt.gensalt()));
            s.setString(6, user.getRole().name());
            s.executeUpdate();
        }
    }

    public Optional<User> login(String username, String plainPassword) throws SQLException {
        String sql = "SELECT * FROM users WHERE username = ?";
        try (PreparedStatement s = connection.prepareStatement(sql)) {
            s.setString(1, username);
            try (ResultSet rs = s.executeQuery()) {
                if (!rs.next()) return Optional.empty();
                if (!BCrypt.checkpw(plainPassword, rs.getString("password_hash")))
                    return Optional.empty();
                User u = mapUser(rs);
                u.markLoggedIn();
                return Optional.of(u);
            }
        }
    }

    public Optional<User> getUserById(String id) throws SQLException {
        String sql = "SELECT * FROM users WHERE id = ?";
        try (PreparedStatement s = connection.prepareStatement(sql)) {
            s.setString(1, id);
            try (ResultSet rs = s.executeQuery()) {
                if (!rs.next()) return Optional.empty();
                return Optional.of(mapUser(rs));
            }
        }
    }

    public List<User> getAllUsers() throws SQLException {
        List<User> list = new ArrayList<>();
        String sql = "SELECT * FROM users ORDER BY id ASC";
        try (PreparedStatement s = connection.prepareStatement(sql);
             ResultSet rs = s.executeQuery()) {
            while (rs.next()) list.add(mapUser(rs));
        }
        return list;
    }

    private User mapUser(ResultSet rs) throws SQLException {
        return new User(
                String.valueOf(rs.getInt("id")),
                rs.getString("name"),
                rs.getString("email"),
                rs.getString("phone_number"),
                rs.getString("username"),
                User.Role.valueOf(rs.getString("role")));
    }
}