name: Build and Analyze

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    name: Build and SonarCloud Scan
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@a12a3943b4bdde767164f792f33f40b04645d846
        with:
          fetch-depth: 0

      - name: Set up JDK 17
        uses: actions/setup-java@cd89f46ac9d01407894225f350157564c9c7cee2
        with:
          distribution: temurin
          java-version: '17'

      - name: Cache Maven packages
        uses: actions/cache@88522ab9f39a2ea568f7027eddc7d8d8bc9d59c8
        with:
          path: ~/.m2
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      - name: Build, Test & Coverage
        run: mvn -B verify --file pom.xml

      - name: Copy Dependencies for Sonar
        run: mvn dependency:copy-dependencies -DoutputDirectory=target/dependency

      - name: SonarCloud Scan
        uses: SonarSource/sonarqube-scan-action@f0760eaa3c2101c8ef0e7226dcd6738fc47e802b
        with:
          args: >
            -Dsonar.projectKey=sana-noora_Appoinmentsystem
            -Dsonar.organization=sana-noora
            -Dsonar.host.url=https://sonarcloud.io
            -Dsonar.java.binaries=target/classes
            -Dsonar.java.libraries=target/dependency/*.jar
            -Dsonar.coverage.jacoco.xmlReportPaths=target/site/jacoco/jacoco.xml
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          EMAIL_USERNAME: ${{ secrets.EMAIL_USERNAME }}
          EMAIL_PASSWORD: ${{ secrets.EMAIL_PASSWORD }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
