name: Build and Analyze

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    name: Build and SonarCloud Scan
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:15
        env:
          POSTGRES_DB: appointmentdb
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '17'

      # ✅ مهم جدًا: إنشاء .env قبل تشغيل التستات
      - name: Create .env file for tests
        run: |
          echo "EMAIL_USERNAME=${{ secrets.EMAIL_USERNAME }}" > .env
          echo "EMAIL_PASSWORD=${{ secrets.EMAIL_PASSWORD }}" >> .env

      - name: Cache Maven packages
        uses: actions/cache@v4
        with:
          path: ~/.m2
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      - name: Build, Test & Coverage
        run: mvn -B verify --file pom.xml
        env:
          DB_URL: jdbc:postgresql://localhost:5432/appointmentdb
          DB_USER: postgres
          DB_PASSWORD: postgres

      - name: Copy Dependencies for Sonar
        run: mvn dependency:copy-dependencies -DoutputDirectory=target/dependency

      - name: SonarCloud Scan
        uses: SonarSource/sonarqube-scan-action@v2
        with:
          args: >
            -Dsonar.projectKey=sana-noora_Appoinmentsystem
            -Dsonar.organization=sana-noora
            -Dsonar.host.url=https://sonarcloud.io
            -Dsonar.java.binaries=target/classes
            -Dsonar.java.libraries=target/dependency/*.jar
            -Dsonar.coverage.jacoco.xmlReportPaths=target/site/jacoco/jacoco.xml
            -Dsonar.coverage.exclusions=**/src/test/java/**,**/doc/**,**/doc/**/*.java,**/presentation/**,**/presentation/**/*.java,**/GenerateHash.java
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          EMAIL_USERNAME: ${{ secrets.EMAIL_USERNAME }}
          EMAIL_PASSWORD: ${{ secrets.EMAIL_PASSWORD }}
